[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++23", "-Wall", "-Wextra", "-O2", "-I", "./external/ac-library"]

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = ["-std=c++23", "-Wall", "-Wextra", "-O2", "-I", "./external/ac-library"]
