name: c++ lint

on:
  pull_request:
    branches:
      - "main"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run clang-format
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          version: "21"
          style: 'file'
          tidy-checks: '-*'

      - name: Fail if format issues found
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

  clang-tidy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run clang-tidy
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          version: "21"
          style: ''
          tidy-checks: 'boost-*,bugprone-*,performance-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*,readability-*,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-readability-identifier-naming,-llvm-header-guard,-llvmlibc-*,-misc-non-private-member-variables-in-classes'
          database: "."
          # extra-args: '-std=c++23 -Wall -Wextra -I. -I./external/ac-library'

      - name: Log issue count
        run: |
          echo "Total issues found: ${{ steps.linter.outputs.checks-failed }}."

      - name: Fail if format issues found
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
